import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <p>Please login with guest account.</p>
          <p className={styles.colorpale}>Username:Guest01</p>
          <p className={styles.colorpale}>Password:Pass</p>
        </h1>

        <div className={styles.grid}>
          <form action="./main" method="post">
            <h2>Login!</h2>
            <p>Username</p>
            <input type="text" name="username" />
            <p>Password</p>
            <input type="password" name="password" />
            <input type="submit" value="ログイン" />
          </form>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
